services:
  - type: web
    name: ml-chatbot-pipeline
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
